### ISSUE TITLE
Django 3 support

### ISSUE THREAD

**Issue by e-belair** [maxirobaina/django-firebird#110]
Hi, is there a way to make it working with Django 3 ?
I try to build an api with django rest framework but I get the following error:
django.core.exceptions.ImproperlyConfigured: 'firebird' isn't an available database backend.

**Comment by eriklesbr** [comment]
Olá @e-belair, conseguiu de alguma forma conectar o firebird ao Django 3?
Achei este post https://pypi.org/project/djfirebirdsql/0.2.0/ mas mesmo com ele não conseguir realizar a configuração corretamente! Ocorreu erros na migração, alertando erros com o sql. Se conseguiu realizar a configuração e puder me ajudar com isso eu agradeço, caso não tenha conseguido tente com esse link acima e ver se consegue realizar a conexão!

**Comment by tcpulinux** [comment]
I've made some progress on this, but have a different error now.
System: 
debian 10 (Buster)
python 3.7
fdb 2.0.1
django-firebird 1.11
firebird 2.5.9

I have done the following in my virtualbox vm...
ln -s /usr/lib/python3/dist-packages/firebird /usr/local/lib/python3.7/dist-packages/django/db/backend/firebird
ln -s /usr/lib/python3/dist-packages/six.py /usr/local/lib/python3.7/dist-packages/django/utils/six.py

In deprecation.py duplicate RemovedInDjango21Warning section from RemovedInDjango31Warning and save

I had to reference my database in settings.py like this...
DATABASES = {
    'default':{
       'ENGINE': 'django.db.backends.firebird',
        'NAME': '/fbdata/fbdjango.fdb',
        'USER' : 'SYSDBA',
        'PASSWORD': '****',
        'HOST' : 'localhost',
        'PORT' : '3050',
    }
}

When I migrate a project that works with Sqlite from the django tutorial, I get...
~/firstdj$ python3 manage.py migrate
Traceback (most recent call last):
  File "manage.py", line 21, in <module>
    main()
  File "manage.py", line 17, in main
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.7/dist-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.7/dist-packages/django/core/management/__init__.py", line 395, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.7/dist-packages/django/core/management/base.py", line 328, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.7/dist-packages/django/core/management/base.py", line 366, in execute
    self.check()
  File "/usr/local/lib/python3.7/dist-packages/django/core/management/base.py", line 395, in check
    include_deployment_checks=include_deployment_checks,
  File "/usr/local/lib/python3.7/dist-packages/django/core/management/commands/migrate.py", line 64, in _run_checks
    issues.extend(super()._run_checks(**kwargs))
  File "/usr/local/lib/python3.7/dist-packages/django/core/management/base.py", line 382, in _run_checks
    return checks.run_checks(**kwargs)
  File "/usr/local/lib/python3.7/dist-packages/django/core/checks/registry.py", line 72, in run_checks
    new_errors = check(app_configs=app_configs)
  File "/usr/local/lib/python3.7/dist-packages/django/core/checks/model_checks.py", line 34, in check_all_models
    errors.extend(model.check(**kwargs))
  File "/usr/local/lib/python3.7/dist-packages/django/db/models/base.py", line 1254, in check
    *cls._check_fields(**kwargs),
  File "/usr/local/lib/python3.7/dist-packages/django/db/models/base.py", line 1333, in _check_fields
    errors.extend(field.check(**kwargs))
  File "/usr/local/lib/python3.7/dist-packages/django/db/models/fields/__init__.py", line 2338, in check
    *super().check(**kwargs),
  File "/usr/local/lib/python3.7/dist-packages/django/db/models/fields/__init__.py", line 1722, in check
    *super().check(**kwargs),
  File "/usr/local/lib/python3.7/dist-packages/django/db/models/fields/__init__.py", line 208, in check
    *self._check_validators(),
  File "/usr/local/lib/python3.7/dist-packages/django/db/models/fields/__init__.py", line 350, in _check_validators
    for i, validator in enumerate(self.validators):
  File "/usr/local/lib/python3.7/dist-packages/django/utils/functional.py", line 48, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.7/dist-packages/django/db/models/fields/__init__.py", line 1744, in validators
    min_value, max_value = connection.ops.integer_field_range(internal_type)
  File "/usr/local/lib/python3.7/dist-packages/django/db/backends/base/operations.py", line 623, in integer_field_range
    return self.integer_field_ranges[internal_type]
KeyError: 'AutoField'
~/firstdj$ 

I've go into operations.py and found that for some reason, integer_field_range doesn't contain the three Autofield types even though the definition has them.  A copy/paste to python3 works fine and I'm at a loss as to why they are missing when the call is made.
BTW, what is the last tested/supported version of django on which this works?
Thanks!

**Comment by carltongibson** [comment]
Hello. Can I ask if there's any update on the status of this one? We're reviewing the list of 3rd party backends, and I'm wondering if this project is still going? Is there a release planned before Django 3.1?

**Comment by mariuz** [comment]
The stable version corresponds with django 2.2 and live into stable/2.2.x branch. The current master branch of this repository is being developed under django 3.0.x.  (pre alpha) https://github.com/maxirobaina/django-firebird/commit/d66ff96353cf8cfc5a9e5c0861947abb55c9b680

**Comment by david-geiger** [comment]
Hi,

Current master branch is incompatible with django 3.0 and/or 3.1 due to a missing six import:

>   File "/home/iurt/rpmbuild/BUILD/django-firebird-20181213/firebird/expressions.py", line 3, in <module>
    from django.utils import six
ImportError: cannot import name 'six' from 'django.utils' (/usr/lib/python3.8/site-packages/django/utils/__init__.py)
error: Bad exit status from /home/iurt/rpmbuild/tmp/rpm-tmp.qhltXv (%build)

This "/django/utils/six.py" module was dropped since django 3.0

Regards,
David

**Comment by mariuz** [comment]
@david-geiger , thanks now is removed 

https://github.com/maxirobaina/django-firebird/commit/fdca4f631d289194a91c01bbedf05e7920fbb910

**Comment by maxirobaina** [comment]
Hi @wolandius 
Yes, most probably the next month we get back, first trying to update to django 3.2 LTS and then go to the next LST version of django. Stay tuned!!
Regards

**Comment by vinitkumar** [comment]
@maxirobaina Just made a PR that does that. https://github.com/maxirobaina/django-firebird/pull/126

Please check.

**Comment by e-belair** [comment]
I'm not using it anymore but thanks for your PR!
