### ISSUE TITLE
TypeError: convert_booleanfield_value() missing 1 required positional argument: 'context'

### ISSUE THREAD

**Issue by devops724** [maxirobaina/django-firebird#137]
Hi, after fill login form and press login button in admin i get this error
Internal Server Error: /api-admin/login/
Traceback (most recent call last):
  File "/home/user/env/lib/python3.9/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/user/env/lib/python3.9/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/user/env/lib/python3.9/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/user/env/lib/python3.9/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/user/env/lib/python3.9/site-packages/django/contrib/admin/sites.py", line 407, in login
    return LoginView.as_view(**defaults)(request)
  File "/home/user/env/lib/python3.9/site-packages/django/views/generic/base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/user/env/lib/python3.9/site-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/home/user/env/lib/python3.9/site-packages/django/views/decorators/debug.py", line 76, in sensitive_post_parameters_wrapper
    return view(request, *args, **kwargs)
  File "/home/user/env/lib/python3.9/site-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/home/user/env/lib/python3.9/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/user/env/lib/python3.9/site-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/home/user/env/lib/python3.9/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/user/env/lib/python3.9/site-packages/django/contrib/auth/views.py", line 63, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/home/user/env/lib/python3.9/site-packages/django/views/generic/base.py", line 97, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/user/env/lib/python3.9/site-packages/django/views/generic/edit.py", line 141, in post
    if form.is_valid():
  File "/home/user/env/lib/python3.9/site-packages/django/forms/forms.py", line 180, in is_valid
    return self.is_bound and not self.errors
  File "/home/user/env/lib/python3.9/site-packages/django/forms/forms.py", line 175, in errors
    self.full_clean()
  File "/home/user/env/lib/python3.9/site-packages/django/forms/forms.py", line 377, in full_clean
    self._clean_form()
  File "/home/user/env/lib/python3.9/site-packages/django/forms/forms.py", line 404, in _clean_form
    cleaned_data = self.clean()
  File "/home/user/env/lib/python3.9/site-packages/django/contrib/auth/forms.py", line 214, in clean
    self.user_cache = authenticate(self.request, username=username, password=password)
  File "/home/user/env/lib/python3.9/site-packages/django/contrib/auth/__init__.py", line 72, in authenticate
    user = backend.authenticate(request, **credentials)
  File "/home/user/env/lib/python3.9/site-packages/django/contrib/auth/backends.py", line 46, in authenticate
    user = UserModel._default_manager.get_by_natural_key(username)
  File "/home/user/env/lib/python3.9/site-packages/django/contrib/auth/base_user.py", line 44, in get_by_natural_key
    return self.get(**{self.model.USERNAME_FIELD: username})
  File "/home/user/env/lib/python3.9/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/user/env/lib/python3.9/site-packages/django/db/models/query.py", line 411, in get
    num = len(clone)
  File "/home/user/env/lib/python3.9/site-packages/django/db/models/query.py", line 258, in __len__
    self._fetch_all()
  File "/home/user/env/lib/python3.9/site-packages/django/db/models/query.py", line 1261, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/home/user/env/lib/python3.9/site-packages/django/db/models/query.py", line 74, in __iter__
    for row in compiler.results_iter(results):
  File "/home/user/env/lib/python3.9/site-packages/django/db/models/sql/compiler.py", line 1098, in apply_converters
    value = converter(value, expression, connection)
TypeError: convert_booleanfield_value() missing 1 required positional argument: 'context'
[13/Nov/2022 15:11:46] "POST /api-admin/login/?next=/api-admin/ HTTP/1.1" 500 244820
python 3.0.14
django firebird 2.2

**Comment by marcosatinel** [comment]
value = converter(value, expression, connection, context=None) 
pass the error...
