### ISSUE TITLE
TypeError: _alter_column_type_sql() takes exactly 5 arguments (4 given)

### ISSUE THREAD

**Issue by maxirobaina** [maxirobaina/django-firebird#52]
======================================================================
ERROR: test_rename (schema.tests.SchemaTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/maxi/projects/django/django-firebird/forks/github/django-firebird/tests/test_main/schema/tests.py", line 393, in test_rename
    strict=True,
  File "/usr/local/lib/python2.7/dist-packages/django/db/backends/schema.py", line 470, in alter_field
    self._alter_field(model, old_field, new_field, old_type, new_type, old_db_params, new_db_params, strict)
  File "/usr/local/lib/python2.7/dist-packages/firebird/schema.py", line 138, in _alter_field
    fragment, other_actions = self._alter_column_type_sql(model._meta.db_table, new_field.column, new_type)
TypeError: _alter_column_type_sql() takes exactly 5 arguments (4 given)

**Comment by maxirobaina** [comment]
Solved with issue #29 
Schema implementation was started with django 1.7 beta version. 
The commit https://github.com/maxirobaina/django-firebird/commit/fc768c9860a7e791a446ea6948f8b6830246212d fix several issues.
