### ISSUE TITLE
Support for firebird 3

### ISSUE THREAD

**Issue by davevt** [maxirobaina/django-firebird#68]
Hi There,
While testing with firebird 3 - suppose alter table etc. should be used instead...
**UPDATE operation is not allowed for system table RDB$RELATION_FIELDS**
pls let me know if more info is required - see below
Many thanks,
dvt

$ python3 manage.py migrate
Operations to perform:
  Apply all migrations: admin, auth, contenttypes, sessions
Running migrations:
  Applying contenttypes.0001_initial... OK
  Applying auth.0001_initial... OK
  Applying admin.0001_initial... OK
  Applying admin.0002_logentry_remove_auto_add... OK
  Applying contenttypes.0002_remove_content_type_name...Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.5/dist-packages/django_firebird-1.9a0-py3.5.egg/firebird/base.py", line 236, in execute
    return self.cursor.execute(q, params)
  File "/usr/local/lib/python3.5/dist-packages/fdb/fbcore.py", line 3576, in execute
    self._ps._execute(parameters)
  File "/usr/local/lib/python3.5/dist-packages/fdb/fbcore.py", line 3291, in _execute
    "Error while executing SQL statement:")
fdb.fbcore.DatabaseError: ('Error while executing SQL statement:\n- SQLCODE: -902\n- UPDATE operation is not allowed for system table RDB$RELATION_FIELDS', -902, 335545030)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/lib/python3/dist-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/usr/lib/python3/dist-packages/django/core/management/__init__.py", line 359, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/lib/python3/dist-packages/django/core/management/base.py", line 294, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/lib/python3/dist-packages/django/core/management/base.py", line 345, in execute
    output = self.handle(*args, **options)
  File "/usr/lib/python3/dist-packages/django/core/management/commands/migrate.py", line 204, in handle
    fake_initial=fake_initial,
  File "/usr/lib/python3/dist-packages/django/db/migrations/executor.py", line 115, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/usr/lib/python3/dist-packages/django/db/migrations/executor.py", line 145, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/usr/lib/python3/dist-packages/django/db/migrations/executor.py", line 244, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/usr/lib/python3/dist-packages/django/db/migrations/migration.py", line 129, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/usr/lib/python3/dist-packages/django/db/migrations/operations/fields.py", line 204, in database_forwards
    schema_editor.alter_field(from_model, from_field, to_field)
  File "/usr/lib/python3/dist-packages/django/db/backends/base/schema.py", line 495, in alter_field
    old_db_params, new_db_params, strict)
  File "/usr/local/lib/python3.5/dist-packages/django_firebird-1.9a0-py3.5.egg/firebird/schema.py", line 262, in _alter_field
    self.execute(sql, params)
  File "/usr/local/lib/python3.5/dist-packages/django_firebird-1.9a0-py3.5.egg/firebird/schema.py", line 404, in execute
    cursor.execute(sql, params)
  File "/usr/lib/python3/dist-packages/django/db/backends/utils.py", line 79, in execute
    return super(CursorDebugWrapper, self).execute(sql, params)
  File "/usr/lib/python3/dist-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/usr/lib/python3/dist-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/usr/lib/python3/dist-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/usr/lib/python3/dist-packages/django/db/backends/utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.5/dist-packages/django_firebird-1.9a0-py3.5.egg/firebird/base.py", line 236, in execute
    return self.cursor.execute(q, params)
  File "/usr/local/lib/python3.5/dist-packages/fdb/fbcore.py", line 3576, in execute
    self._ps._execute(parameters)
  File "/usr/local/lib/python3.5/dist-packages/fdb/fbcore.py", line 3291, in _execute
    "Error while executing SQL statement:")
django.db.utils.DatabaseError: ('Error while executing SQL statement:\n- SQLCODE: -902\n- UPDATE operation is not allowed for system table RDB$RELATION_FIELDS', -902, 335545030)

**Comment by gustavodiego01** [comment]
Hello, 
cual es la compatibilidad para usar Firebird 3.02 ??

Gracias

**Comment by davevt** [comment]
Hola,

[https://www.firebirdsql.org/file/documentation/release_notes/html/en/3_0/rnfb30-compat-systables.html](url)
[https://www.firebirdsql.org/file/documentation/release_notes/html/en/3_0/rnfb30-ddl-enhance.html](url)

SQL> show version;
ISQL Version: LI-V3.0.1.32609 Firebird 3.0
Server version:
Firebird/Linux/Intel/i386 (access method), version "LI-V3.0.1.32609 Firebird 3.0"
on disk structure version 12.0

Saludos y gracias,
D

**Comment by maxirobaina** [comment]
Hi @davevt,

Firebird 3 is not supported yet.
Regards.

**Comment by toninhonunes** [comment]
Hi Maxi,

I have used Firebird 3.02 and Django 1.10 on django-firebird and it's working very well in production. But just only to query and to change data somefield in database. It's saving the data no problems. I will a lot use the django-firebird, there are plan to support and keep on that driver?

Regards,

Antonio.

**Comment by maxirobaina** [comment]
Hi Antonio,

I'm glad that it be useful for you. 
Currently, the current version (in master branch) is based in django 1.9, I don't tested it in django 1.10. I hope this year to invest more time in this project, maybe jumping directly to 1.11 witch is the next django LTS  release and then to 2.0
The update to firebird 3.x perhaps imply broken the compatibility with firebird 2, so this need more research.

Of course, PR are always welcome :smiley: 

Best regards.
Maxi.

**Comment by viniciusban** [comment]
Is there any news about supporting Firebird 3?

**Comment by jsgilberto** [comment]
> Is there any news about supporting Firebird 3?

I managed to find a "solution" but I haven't verified the side effects of it.

**Comment by toshiroakio** [comment]
Hello. Please show your solution

**Comment by toshiroakio** [comment]
into **schema.py**
`def _alter_column_set_null(self, table_name, column_name, is_null):
        fb_ver = str(self.connection.connection.engine_version).split('.')
        if fb_ver and len(fb_ver) > 0 and int(fb_ver[0]) >= 3:
            sql = "ALTER TABLE %(table_name)s ALTER %(column)s %(null_flag)s NOT NULL"
            null_flag = 'DROP' if is_null else 'SET'
        else:
            sql = """
                UPDATE RDB$RELATION_FIELDS SET RDB$NULL_FLAG = %(null_flag)s
                WHERE RDB$FIELD_NAME = '%(column)s'
                AND RDB$RELATION_NAME = '%(table_name)s'
            """
            null_flag = 'NULL' if is_null else '1'
        return sql % {
            'null_flag': null_flag,
            'column': column_name.upper(),
            'table_name': table_name.upper()
        }`

**Comment by ribeiroti** [comment]
Hi @maxirobaina @toshiroakio Firebird 3.0 is not yet supported?

**Comment by maxirobaina** [comment]
Hi @ribeiroti  I'm working on it right now. I hope to have news soon.

Regards

**Comment by gustavodiego01** [comment]
Super

**Comment by mariuz** [comment]
Some of the Firebird 3 issues are fixed by https://github.com/maxirobaina/django-firebird/pull/111

I guess this can be closed
