### ISSUE TITLE
Error with migrate of django-firebird

### ISSUE THREAD

**Issue by omegaplu** [maxirobaina/django-firebird#97]
Running the migrate command with django-firebird will result in the following error:

It's a problem associated with automatically generated user tables, so it's hard to fix it.
I would appreciate any help on how to resolve it.

```
  Operations to perform:
  Apply all migrations: admin, auth, contenttypes, mdlservice, sessions
Running migrations:
  Applying auth.0001_initial... OK
  Applying admin.0001_initial... OK
  Applying admin.0002_logentry_remove_auto_add... OK
  Applying auth.0002_alter_permission_name_max_length... OK
  Applying auth.0003_alter_user_email_max_length... OK
  Applying auth.0004_alter_user_username_opts... OK
  Applying auth.0005_alter_user_last_login_null... OK
  Applying auth.0006_require_contenttypes_0002... OK
  Applying auth.0007_alter_validators_add_error_messages... OK
  Applying auth.0008_alter_user_username_max_length...Traceback (most recent call last):
  File "C:\Users\emptyspear\AppData\Local\Programs\Python\Python35-32\lib\site-packages\django\db\backends\utils.py", line 64, in execute
    return self.cursor.execute(sql, params)
  File "C:\Users\emptyspear\AppData\Local\Programs\Python\Python35-32\lib\site-packages\firebird\base.py", line 236, in execute
    return self.cursor.execute(q, params)
  File "C:\Users\emptyspear\AppData\Local\Programs\Python\Python35-32\lib\site-packages\fdb\fbcore.py", line 3627, in execute
    self._ps._execute(parameters)
  File "C:\Users\emptyspear\AppData\Local\Programs\Python\Python35-32\lib\site-packages\fdb\fbcore.py", line 3333, in _execute
    "Error while executing SQL statement:")
fdb.fbcore.DatabaseError: ('Error while executing SQL statement:\n- SQLCODE: -607\n- unsuccessful metadata update\n- MODIFY RDB$RELATION_FIELDS failed\n- action cancelled by trigger (1) to preserve data integrity\n- Cannot update index segment used by an Integrity Constraint', -607, 335544351)
```

The development environment is as follows

os : windows10
python : 3.5.4
django : 1.10.8
fdb : 2.0.0
firebird : 2.5(32bit)

**Comment by maxirobaina** [comment]
Hi @omegaplu 
Does you have User.username as foreign key to another table maybe?
Running auth.0008_alter_user_username_max_length  firebird will try to change the size on username field on auth_user model. If you use this on a, by example, store procedure, trigger or view, Firebird can't alter it.
It seem related to issue #82 (which was solved)
