### ISSUE TITLE
No Module Named firebird in Django 1.8 Firebird 2.5 and IIS 10

### ISSUE THREAD

**Issue by SaMoSe12** [maxirobaina/django-firebird#98]
Hello, I'm stuck in this Error, I've tried reinstalling django-firebird with no avail. 
The error says: 

> Traceback (most recent call last):
  File "C:\Python3632\lib\site-packages\django\db\utils.py", line 111, in load_backend
    return import_module('%s.base' % backend_name)
  File "C:\Python3632\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'firebird'

My pip freeze: 
 

> Django==1.8
django-firebird==1.9.1
fdb==2.0.0
future==0.16.0
PyMySQL==0.8.1
virtualenv==15.2.0
wfastcgi==3.0.0

The settings.py DATABASES: 

`'default': {
        'ENGINE': 'firebird',
        'NAME': 'C:\Bases de datos\Ejemplos\DB.FDB',
        'USER': 'SYSDBA',
        'PASSWORD':'masterkey',
        'HOST':'192.168.15.196',
        'PORT':'3050'
        }`

**Comment by maxirobaina** [comment]
It seems like python can't found the firebird package into your environment.
Is django-firebird installed into C:\Python3632\lib\site-packages ?

If you run Python from a command line console, and do a import firebird, Do you get any error?

Anyway, I suggest you use virtualenv to isolate all environment context.

**Comment by SaMoSe12** [comment]
There is a problem when using virtualenvs, but it's not from django-firebird is on the iis i think. Probably it's due of my inexperience.
I'm getting another Error now, it says. 

> Exception at /admin/login/
The location of Firebird Client Library could not be determined.

This only appears in the browser because in the console there was no error (after I placed the fbclient.dll)
